version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: game_local
      POSTGRES_USER: game_local
      POSTGRES_PASSWORD: game_local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
