server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/game_local
    username: game_local
    password: game_local

  boot:
    admin:
      client:
        url: http://localhost:8080

  data:
    redis:
      host: localhost
      port: 6379

application:
  Environment: local